### ISSUE TITLE
Finish connecting the Details Page and the event handler to open the article details.

### ISSUE THREAD

**Issue by jcstang** [jcstang/not-reddit#4]

**Comment by jcstang** [comment]
@Graham91 I'm having a hard time with this one. because I was able to pass data to a details page, i'm not sure how we can go back to the home "page". We can cut it altogether if you got something else working.

**Comment by Graham91** [comment]
we could just resend revised data on upload of the home page? Then it doesn't have to go backwards. since we would be making the changes in the data base anyways..
